function [a,b,c,d] = processArgsDemoFun(varargin)
   [a,b,c,d] = processArgs(varargin ,...
   '*-first'       , []             ,...
   '*+-second'     , 'foo'      ,...
   '-third'        , 3             ,...
   '+-fourth'      , 4             );
 fprintf('a %d, b %s, c %d, d %d\n', a, b, c, d);
 end 
